apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-config
data:
  spark-defaults.conf: |
    # --- CONEXÃO COM O MASTER ---
    spark.master                     spark://spark-master-service:7077
    
    # --- REDE (DRIVER NO HOST) ---
    spark.driver.host                192.168.15.9
    spark.driver.bindAddress         0.0.0.0
    
    # --- PACOTES (S3 + AWS SDK + POSTGRES) ---
    spark.jars.packages              org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262,org.postgresql:postgresql:42.6.0
    
    # --- ARMAZÉM S3 (GLOBAL) ---
    spark.sql.warehouse.dir          s3a://lakehouse/warehouse/
    spark.hadoop.fs.s3a.endpoint     http://192.168.15.9:9000
    spark.hadoop.fs.s3a.path.style.access  true
    spark.hadoop.fs.s3a.impl         org.apache.hadoop.fs.s3a.S3AFileSystem
    spark.hadoop.fs.s3a.connection.ssl.enabled  false
    
    # --- CREDENCIAIS S3 (Lendo das Variáveis de Ambiente) ---
    spark.hadoop.fs.s3a.access.key   ${env:AWS_ACCESS_KEY_ID}
    spark.hadoop.fs.s3a.secret.key   ${env:AWS_SECRET_ACCESS_KEY}
    
    # --- OTIMIZAÇÃO PARA ANDROID (BUFFER NA RAM + GZIP) ---
    spark.hadoop.fs.s3a.fast.upload        true
    spark.hadoop.fs.s3a.fast.upload.buffer bytebuffer
    spark.sql.parquet.compression.codec    gzip
    
    # --- METASTORE (POSTGRES) - O ELO PERDIDO ---
    # Aqui ensinamos o Spark a ler as variáveis que injetamos no Deployment
    spark.hadoop.javax.jdo.option.ConnectionURL jdbc:postgresql://${env:METASTORE_HOST}:${env:METASTORE_PORT}/${env:METASTORE_DB}
    spark.hadoop.javax.jdo.option.ConnectionDriverName org.postgresql.Driver
    spark.hadoop.javax.jdo.option.ConnectionUserName ${env:METASTORE_USER}
    spark.hadoop.javax.jdo.option.ConnectionPassword ${env:METASTORE_PASSWORD}
