apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: data-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: apache/spark:3.5.0
        command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
        ports:
        - containerPort: 7077
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-svc
  namespace: data-ops
spec:
  type: LoadBalancer
  selector:
    app: spark-master
  ports:
    - name: cluster
      port: 7077
      targetPort: 7077
    - name: webui
      port: 8080
      targetPort: 8080
